# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    branches:
      - "main"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read

jobs:
  poetry-build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Build release distributions
        run: |
          poetry self add poetry-git-version-plugin
          poetry git-version
          poetry build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - poetry-build
    permissions:
      contents: write # Release
      discussions: write # Discussions
      id-token: write # Pypi

    environment:
      name: pypi
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: "CHANGELOG.md"

      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          files: dist/*
          discussion_category_name: Announcements

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/